#!/usr/bin/env bash
#
# build-report.sh — run a report on the opsman VM and render a PDF locally.
#
#   ./build-report.sh            # health check  -> health-report.{md,html,pdf}
#   ./build-report.sh health     # same as above
#   ./build-report.sh cert       # cert rotation -> cert-rotation-report.{md,html,pdf}
#   FOUNDATION=FOG ./build-report.sh cert   # set the foundation name in the title
#
# Pipeline: <script> --markdown  (on opsman, over SSH)
#        -> <out>.md
#        -> pandoc (standalone, embedded CSS)  -> <out>.html
#        -> Chrome headless --print-to-pdf     -> <out>.pdf
#
# Requires (on this Mac): pandoc and Google Chrome. Run from the repo directory.

set -euo pipefail
cd "$(dirname "$0")"

MODE="${1:-health}"
case "$MODE" in
  health)
    REMOTE_SCRIPT='~/pcf-health-check.sh'; OUT='health-report'
    TITLE_SUFFIX='Foundation Health Check'; VALIDATE='Generated by';;
  cert|cert-rotation)
    REMOTE_SCRIPT='~/cert-rotation-estimate.sh'; OUT='cert-rotation-report'
    TITLE_SUFFIX='Certificate Rotation Estimate'; VALIDATE='Certificate Rotation Estimate';;
  *)
    echo "usage: $0 [health|cert]   (default: health)" >&2; exit 2;;
esac

OPSMAN="${OPSMAN:-ubuntu@192.168.2.85}"
KEY="${KEY:-$HOME/.ssh/id_ed25519}"
CHROME="${CHROME:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"
# Foundation name for the report title (e.g. FOUNDATION=FOG ./build-report.sh cert).
FOUNDATION="${FOUNDATION:-}"
PAGETITLE="PCF${FOUNDATION:+ $FOUNDATION} ${TITLE_SUFFIX}"
SSH_OPTS=(-o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i "$KEY")

echo "[1/3] Running ${MODE} report on ${OPSMAN} ..."
# Both scripts exit 0/1/2 (clean/warnings/critical); a non-zero verdict is not a
# build failure, so don't let pipefail+set -e abort here. Validate by content.
REMOTE_CMD="${REMOTE_SCRIPT} --markdown"
[[ -n "$FOUNDATION" ]] && REMOTE_CMD="FOUNDATION_NAME='${FOUNDATION}' ${REMOTE_CMD}"
ssh "${SSH_OPTS[@]}" "$OPSMAN" "$REMOTE_CMD" 2>/dev/null \
  | grep -v 'Unauthorized use\|subject to logging' > "${OUT}.md" || true
grep -q "$VALIDATE" "${OUT}.md" || { echo "ERROR: report incomplete (no '${VALIDATE}')"; exit 1; }
echo "      -> ${OUT}.md ($(wc -l < "${OUT}.md") lines)"

echo "[2/3] pandoc -> HTML ..."
pandoc "${OUT}.md" -o "${OUT}.html" --standalone --embed-resources \
  --metadata pagetitle="$PAGETITLE" -c report-style.css \
  --include-before-body report-header.html

echo "[3/3] Chrome headless -> PDF ..."
"$CHROME" --headless=new --disable-gpu --no-pdf-header-footer \
  --print-to-pdf="${OUT}.pdf" "file://$PWD/${OUT}.html" 2>/dev/null

echo "Done:"; ls -lh "${OUT}.md" "${OUT}.html" "${OUT}.pdf" | awk '{print "  "$9"  "$5}'
