#!/usr/bin/env bash
#
# build-report.sh — run the health check on the opsman VM and render a PDF locally.
#
# Pipeline: pcf-health-check.sh --markdown  (on opsman, over SSH)
#        -> health-report.md
#        -> pandoc (standalone, embedded CSS)  -> health-report.html
#        -> Chrome headless --print-to-pdf     -> health-report.pdf
#
# Requires (on this Mac): pandoc and Google Chrome. Run from the repo directory.

set -euo pipefail
cd "$(dirname "$0")"

OPSMAN="${OPSMAN:-ubuntu@192.168.2.85}"
KEY="${KEY:-$HOME/.ssh/id_ed25519}"
CHROME="${CHROME:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"
# Foundation name for the report title (e.g. FOUNDATION=FOG ./build-report.sh).
FOUNDATION="${FOUNDATION:-}"
SSH_OPTS=(-o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i "$KEY")

echo "[1/3] Running health check on ${OPSMAN} ..."
# The check exits 0/1/2 (healthy/warnings/critical); a non-zero verdict is not a
# build failure, so don't let pipefail+set -e abort here. Validate by content.
REMOTE_CMD='~/pcf-health-check.sh --markdown'
[[ -n "$FOUNDATION" ]] && REMOTE_CMD="FOUNDATION_NAME='${FOUNDATION}' ${REMOTE_CMD}"
ssh "${SSH_OPTS[@]}" "$OPSMAN" "$REMOTE_CMD" 2>/dev/null \
  | grep -v 'Unauthorized use\|subject to logging' > health-report.md || true
grep -q 'Generated by' health-report.md || { echo "ERROR: report incomplete"; exit 1; }
echo "      -> health-report.md ($(wc -l < health-report.md) lines)"

echo "[2/3] pandoc -> HTML ..."
pandoc health-report.md -o health-report.html --standalone --embed-resources \
  --metadata pagetitle="PCF ${FOUNDATION:-/ TAS} Foundation Health Check" -c report-style.css \
  --include-before-body report-header.html

echo "[3/3] Chrome headless -> PDF ..."
"$CHROME" --headless=new --disable-gpu --no-pdf-header-footer \
  --print-to-pdf=health-report.pdf "file://$PWD/health-report.html" 2>/dev/null

echo "Done:"; ls -lh health-report.md health-report.html health-report.pdf | awk '{print "  "$9"  "$5}'
